server {
    server_name michaelgeorgesinger.com www.michaelgeorgesinger.com;

    root /var/www/michaelgeorgesinger.com/html;
    index index.html;

    access_log /var/log/nginx/michaelgeorgesinger.com.access.log;
    error_log /var/log/nginx/michaelgeorgesinger.com.error.log;

    location = /index {
        return 301 /;
    }

    location / {
        try_files $uri /index.html;
    }

    location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|ico|webp|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
        try_files $uri =404;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/michaelgeorgesinger.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/michaelgeorgesinger.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.michaelgeorgesinger.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = michaelgeorgesinger.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name michaelgeorgesinger.com www.michaelgeorgesinger.com;
    return 404; # managed by Certbot




}